"""made safer

Revision ID: 5753eb7fb4dc
Revises: b094d9e377e5
Create Date: 2026-07-06 19:43:28.718915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5753eb7fb4dc'
down_revision = 'b094d9e377e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('comment_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comment_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_subchessit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subchessit', ['subchessit_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subchessit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=70), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_constraint(batch_op.f('subchessit_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('subchessit_name_key1'), type_='unique')
        batch_op.create_unique_constraint(None, ['title'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subchessit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=70), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('subchessit_name_key1'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('subchessit_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_subchessit_id_fkey'), 'subchessit', ['subchessit_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('post_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_parent_id_fkey'), 'comment', ['parent_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comment_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
