"""Add postvotes table

Revision ID: 904843b53599
Revises: be53ab357eea
Create Date: 2026-07-22 18:43:34.091213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904843b53599'
down_revision = 'be53ab357eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('downvotes')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('downvotes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    op.drop_table('postvotes')
    # ### end Alembic commands ###
