"""keep votes on posts too

Revision ID: a115cc193135
Revises: 904843b53599
Create Date: 2026-07-23 01:43:43.486631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a115cc193135'
down_revision = '904843b53599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('downvotes', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('postvotes', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_post_vote', ['user_id', 'post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postvotes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_post_vote', type_='unique')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('downvotes')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###
