"""timestamps for post,community,comment

Revision ID: a9ad8c63f3d3
Revises: fadfccbd7dfb
Create Date: 2026-07-25 21:39:07.314144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ad8c63f3d3'
down_revision = 'fadfccbd7dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('subchessit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subchessit', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
