"""upvotes downvotes on comments

Revision ID: be53ab357eea
Revises: be995ee3e42a
Create Date: 2026-07-20 15:50:00.632194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be53ab357eea'
down_revision = 'be995ee3e42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('downvotes', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('downvotes')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###
